### ISSUE TITLE
Different ESLint configurations and plugins

### ISSUE THREAD

**Issue by Saicheg** [AdWerx/pronto-ruby#15]
Hey @jbielick!

So after giving a deeper look at current eslint it appears you were right about supporting different plugins and configurations. It works OK for simple installations, but for more advanced installations it is missing support for some advanced configurations and installations.

At this moment I can think of 3 options right now of resolving this problem:

1) Cherry-pick post popular configurations ( standart/google/airbnb ) and plugins ( TOP30 by number of starts ) and 

2) Allow people to have a list of their configurations/plugins to be listed in their `package.json` and run npm install against their package.json before running pronto lint. (See https://github.com/hallee/eslint-action/blob/master/lib/entrypoint.sh for reference )

3) Get rid of eslint pronto runner and suggest people to use separate Github Action for that.

Personally myself would love to stick with #1 or #2, since it really like current solution and would like to keep everything under the same roof.

What are you thoughts over here?

**Comment by jbielick** [comment]
> Cherry-pick post popular configurations ( standart/google/airbnb ) and plugins ( TOP30 by number of starts ) and

I don't think this is a good route because users typically have specific versions in their app—that's a lot of versioning and a moving target.

> Allow people to have a list of their configurations/plugins to be listed in their package.json and run npm install against their package.json before running pronto lint.

I think this would work. Some thoughts:

 - We should only install when the `eslint_npm` runner is being used
 - We'll need to check if they're using `npm` or `yarn` to know which one to install with.
 - It's possible a user can `npm install` to the workspace directory _before_ this action even runs. Have you tried adding an npm install step right before this action? Just curious.
